---
# tasks file for http
- name: Ensure LAMP is at the latest version (RedHat)
  dnf:
    name: 
      - httpd
      - php
      - php-mysqlnd
      - php-cli
      - mysql-server
      - mysql
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Ensure LAMP with php is at the latest version (Debian)
  apt:
    name: 
      - apache2
      - apache2-doc
      - php
      - php-mysql
      - phpmyadmin
      - mariadb-server
      - mariadb-client
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"




