---
# tasks file for jenkins


#repository:

- name: setup Jenkins repo
  copy:
    src:  jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    force: no

- name: Ensure jenkins is at the latest version
  package:
    name: 
      - fontconfig
      - java-17-openjdk
      - jenkins
    state: latest
    update_cache: yes

- name: Ensure that jenkins is started
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes

- name: Open port for jenkins
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  register: fire

- name: Ensure that firewall is restarted
  ansible.builtin.service:
    name: firewalld
    state: restarted
  when: fire.changed