---
# tasks file for postgresql

- name: Ensure postgresql is at the latest version
  package:
    name: postgresql
    state: latest
    update_cache: yes

- name: Ensure that postgresql is started
  ansible.builtin.service:
    name: postgresql
    state: started

