---
# tasks file for postgresql

- name: Ensure postgresql is at the latest version
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: Ensure that postgresql is started
  ansible.builtin.service:
    name: postgresql
    state: started

