---
# tasks file for docker

- name : remove other containers including previous versions of docker (RedHat)
  dnf:
    name:
      - "docker"
      - "docker-client"
      - "docker-client-latest"
      - "docker-common"
      - "docker-latest"
      - "docker-latest-logrotate"
      - "docker-logrotate"
      - "docker-engine"
      - "podman"
      - "runc"
    state: absent
  when: ansible_os_family == "RedHat"

- name : remove other containers including previous versions of docker (Debian)
  apt:
    name:
      - "docker.io"
      - "docker-doc"
      - "docker-compose"
      - "podman-docker"
      - "containerd"
      - "runc"
    state: absent
  when: ansible_os_family == "Debian"

- name: setup repository for docker (RedHat)
  get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: no
  when: ansible_os_family == "RedHat"

- name: setup repository key for docker (Debian)
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: setup repository for docker (Debian)
  copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
    force: no
  when: ansible_os_family == "Debian"


- name: Update Cache and install docker
  package:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Ensure that docker server is started
  service:
    name: docker
    state: started
    enabled: yes
