---

- name: install LAMP servers
  hosts:
    - apps
  become: True
  remote_user: ansible
  roles: 
    - lamp

- name: install jenkins
  hosts: deployments
  become: True
  remote_user: ansible
  roles: 
    - jenkins

- name: install docker
  hosts: 
    - apps
  become: True
  remote_user: ansible
  roles: 
    - docker  
