---

- name: install Apache on apps servers
  hosts:
    - apps
  become: True
  remote_user: ansible
  vars_files:
    - apache/vars/{{ ansible_os_family }}.yml
    - apache/vars/main.yml
  roles: 
    - apache

- name: install mysql on apps servers
  hosts:
    - apps
  become: True
  remote_user: ansible
  vars_files:
    - mysql/vars/{{ ansible_os_family }}.yml
    - mysql/vars/main.yml
  roles: 
    - mysql

- name: install php on apps servers
  hosts:
    - apps
  become: True
  remote_user: ansible
  vars_files:
    - php/vars/{{ ansible_os_family }}.yml
    - php/vars/main.yml
  roles: 
    - php

- name: Setup Wordpress on apps servers
  hosts:
    - apps
  become: True
  remote_user: ansible
  vars_files:
    - wordpress/vars/{{ ansible_os_family }}.yml
    - wordpress/vars/main.yml
  roles: 
    - wordpress