---

- name: setup workstations 
  hosts:
    - workstations 
  become: True
  remote_user: ansible
  tasks:

    - name: install git
      tags: always
      package:
        name : git
        state: latest

    - name: install pip
      tags: always
      package:
        name : python3-pip
        state: latest

    - name: Find EXTERNALLY-MANAGED within /usr/lib for Debian based Distro    
      find:
        path: /usr/lib
        patterns: EXTERNALLY-MANAGED
        recurse: yes
        file_type: file
      register: EMFile
      when: ansible_os_family == "Debian"

    - name: Remove EXTERNALLY-MANAGED file for python for Debian based Distro
      file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ EMFile.files }}" 
      when: ansible_os_family == "Debian"

    - name: install ansible full via pip
      tags: always
      pip: 
        name: ansible
        state: latest

    - name : install unzip
      tags: always
      package:
        name: unzip
        state: latest
    
    - name : unzip awscli
      tags: always
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
        creates: /usr/local/bin/aws
      register: aws_unzipped
    
    - name : install awscli
      tags: always
      shell: /tmp/aws/install
      when: aws_unzipped.changed

    - name: install terraform
      tags: always
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
        creates: /usr/local/bin/terraform

    - name: add vscode repo key for Debian based distro
      tags: always
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc 
        state: present
      when: ansible_os_family == "Debian"
      
    - name: add vscode repo for Debian based distro
      copy:
        src: vscode.list
        dest: /etc/apt/sources.list.d/vscode.list
        force: no
      when: ansible_os_family == "Debian"

    - name: install apt-transport-https for Debian based distro
      tags: always
      package:
        name : apt-transport-https
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: add vscode repo for RedHat based distro
      tags: always
      copy:
        src: vscode.repo
        dest: /etc/yum.repos.d/vscode.repo
      when: ansible_os_family == "RedHat"   

    - name: install vscode
      tags: always
      package:
        name : code
        state: latest
        update_cache: yes


