---

- name: install http server
  hosts:
    - apps
  become: True
  roles: 
    - http

- name: install postgresql
  hosts: dbs
  become: True
  roles: 
    - postgresql

- name: install jenkins
  hosts: others
  become: True
  roles: 
    - jenkins

- name: install jenkins
  hosts: 
    - apps
    - dbs
    - others
  become: True
  roles: 
    - docker  