---
# tasks file for http
- name: Ensure apache with php is at the latest version
  package:
    name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest

- name: Ensure that apache is started
  ansible.builtin.service:
    name: "{{ apache_package }}"
    state: started


