---
# tasks file for http
- name: Ensure apache with php is at the latest version
  package:
    name: 
      - httpd
      - php
    state: latest

- name: Ensure that apache is started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Open port for apache
  firewalld:
    service: http
    permanent: True
    state: enabled
  register: fire

- name: Ensure that firewall is restarted
  ansible.builtin.service:
    name: firewalld
    state: restarted
  when: fire.changed




