---
# tasks file for http
- name: Ensure apache with php is at the latest version
  package:
    name: 
      - httpd
      - php
    state: latest

- name: Ensure that apache is started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Open port for apache
  shell: firewall-cmd --permanent --add-port=80/tcp

- name: Ensure that firewall is restarted
  ansible.builtin.service:
    name: firewalld
    state: restarted




