---
# tasks file for http
- name: Ensure apache is at the latest version
  ansible.builtin.yum:
    name: httpd
    state: present
  when: ansible_distribution == 'Fedora'

- name: Ensure apache is at the latest version
  pkgng: 
    name: apache24
    state: present
  when: ansible_distribution == 'FreeBSD'

- name: Ensure that apache is started
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_distribution == 'Fedora'

- name: Ensure that apache is started
  ansible.builtin.service:
    name: apache24 
    state: started
  when: ansible_distribution == 'FreeBSD'



